source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'YYAppCommonKit_Example', :exclusive => true do
  pod "YYAppCommonKit", :path => "../"
end

target 'YYAppCommonKit_Tests', :exclusive => true do
  pod "YYAppCommonKit", :path => "../"

  
end
